<?php
    $title = 'New thread';
    $this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?php
    $form->setAttribute('action', $this->url('forum', array('action' => 'add')));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('OP'));
    echo $this->formRow($form->get('title'));
    //echo $this->formRow( <---type first post somehow
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();