<?php
    $title = 'Forum index';
    $this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<table class="table">
<tr>
    <th>&nbsp</th>
    <th>Thread</th>
</tr>
<?php foreach ($threadlist as $thread) : ?>
<tr>
    <td><?php echo $thread->id; ?></td>
    <td><a href="<?php echo 'forum/thread/'.$thread->id ?>"><?php echo $thread->title; ?></a></td>
    <td><a href="<?php echo 'forum/delete/'.$thread->id ?>">Delete</a></td>
</tr>
<?php endforeach ?>
</table>
<a href="forum/add">Create a thread</a>