<h3><?php
    session_start();
    echo $thread->title ?></h3>

<ol><?php foreach ($posts as $post) : ?>
    <li><div class="post">
        <h5>Posted by: <?php echo $post->user ?></h1>
        <p><?php echo $post->content; ?></p>
    </div></li>
<?php endforeach ?></ol>

<div class="reply"> <?php
    if(isset($_SESSION['signed_in']) && $_SESSION['signed_in'] == true)
    {
        $form->setAttribute('action', $this->url('thread', array('id' => $thread->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('thread_id'));
        echo $this->formHidden($form->get('post_id'));
        echo $this->formHidden($form->get('user'));
        echo $this->formRow($form->get('content'));
        echo "<br><br>";
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    }
    else
    {
        echo "You must be signed in to post a reply. <a href=/skelApp/public/user/login>Sign in</a> or <a href=/skelApp/public/user/register>register</a>.";
    }
?></div>
<a href="/skelApp/public/forum">Return</a>