<h2>User List</h2>

<table class="table">
<tr>
    <th>ID</th>
    <th>Username</th>
    <th>Password</th>
    <th>Level</th>
</tr>
<?php foreach ($userlist as $user) : ?>
    <tr>
        <td><?php echo $user->user_id; ?></td>
        <td><?php echo $user->username; ?></td>
        <td><?php echo $user->password; ?></td>
        <td><?php
                if ($user->username == 0) echo "User";
                else if($user->username == 0) echo "Admin";
            ?>
        </td>
    </tr>
<?php endforeach ?>
</table>